// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEp7fDYg-qMhPvEbS4CkDL_GJdxKqDd7g',
    appId: '1:1095508831834:web:d67b55c9392df24b6af263',
    messagingSenderId: '1095508831834',
    projectId: 'taskflow-lc',
    authDomain: 'taskflow-lc.firebaseapp.com',
    storageBucket: 'taskflow-lc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYS-Gp32PrYrrvYxbDpuCtVBziNzy1Xw',
    appId: '1:1095508831834:android:8b19ee4491de5f3d6af263',
    messagingSenderId: '1095508831834',
    projectId: 'taskflow-lc',
    storageBucket: 'taskflow-lc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8GiSO26MODEmarkX4SGJHScaKfRdHXgQ',
    appId: '1:1095508831834:ios:6bc81107d4f5e4f26af263',
    messagingSenderId: '1095508831834',
    projectId: 'taskflow-lc',
    storageBucket: 'taskflow-lc.firebasestorage.app',
    iosBundleId: 'com.example.taskflowLc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8GiSO26MODEmarkX4SGJHScaKfRdHXgQ',
    appId: '1:1095508831834:ios:6bc81107d4f5e4f26af263',
    messagingSenderId: '1095508831834',
    projectId: 'taskflow-lc',
    storageBucket: 'taskflow-lc.firebasestorage.app',
    iosBundleId: 'com.example.taskflowLc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEp7fDYg-qMhPvEbS4CkDL_GJdxKqDd7g',
    appId: '1:1095508831834:web:21bd97bc6fc3b0236af263',
    messagingSenderId: '1095508831834',
    projectId: 'taskflow-lc',
    authDomain: 'taskflow-lc.firebaseapp.com',
    storageBucket: 'taskflow-lc.firebasestorage.app',
  );
}
